config:
  - 
    dealear_type: DEALER
    file_name: resources/data/dealers_data.csv
    links:
      - name: ALL
        link: sjuj7h
        scrape: false
        filter: false
        dealer: DEALER
        link_type: list
      - name: SOLD
        link: sjui8e
        scrape: true
        filter: false
        dealer: DEALER
        link_type: list
      - name: IN SALE
        link: sjujf2
        scrape: true
        filter: true
        dealer: DEALER
        link_type: list
  - 
    dealear_type: PRIVATE
    file_name: resources/data/private_data.csv
    links:
      - name: ALL
        link: sjukqi
        scrape: false
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: SOLD
        link: sjukyh
        scrape: true
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: IN SALE
        link: sjuktl
        scrape: true
        filter: true
        dealer: PRIVATE
        link_type: list
  - 
    dealear_type: ALL
    file_name: resources/data/details.csv
    links:
      - name: ALL
        link: sjuhcw
        scrape: false
        filter: false
        dealer: None
        link_type: details
