config:
  - 
    dealear_type: DEALER
    file_name: resources/data/dealers_data.csv
    links:
      - name: ALL
        link: spb1qk
        scrape: false
        filter: false
        dealer: DEALER
        link_type: list
      - name: SOLD
        link: spb1gn
        scrape: true
        filter: false
        dealer: DEALER
        link_type: list
      - name: IN SALE
        link: spb15s
        scrape: true
        filter: true
        dealer: DEALER
        link_type: list
  - 
    dealear_type: PRIVATE
    file_name: resources/data/private_data.csv
    links:
      - name: ALL
        link: spb1wx
        scrape: false
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: SOLD
        link: spb26n
        scrape: true
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: IN SALE
        link: spb21m
        scrape: true
        filter: true
        dealer: PRIVATE
        link_type: list
  - 
    dealear_type: ALL
    file_name: resources/data/details.csv
    links:
      - name: ALL
        link: spb0ir
        scrape: false
        filter: false
        dealer: None
        link_type: details
