config:
  - 
    dealear_type: DEALER
    links:
      - name: ALL
        link: ts2v8t
        scrape: false
        filter: false
        dealer: DEALER
        link_type: list
      - name: SOLD
        link: ts2z36
        scrape: true
        filter: false
        dealer: DEALER
        link_type: list
      - name: IN SALE
        link: ts2yx6
        scrape: true
        filter: true
        dealer: DEALER
        link_type: list
  - 
    dealear_type: PRIVATE
    links:
      - name: ALL
        link: ts2zkk
        scrape: false
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: SOLD
        link: ts2z8m
        scrape: true
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: IN SALE
        link: ts2zdr
        scrape: true
        filter: true
        dealer: PRIVATE
        link_type: list
  - 
    dealear_type: ALL
    links:
      - name: ALL
        link: ts2vsq
        scrape: false
        filter: false
        dealer: None
        link_type: details
