config:
  - 
    dealear_type: DEALER
    file_name: resources/data/dealers_data.csv
    links:
      - name: ALL
        link: se50w3
        scrape: false
        filter: false
        dealer: DEALER
        link_type: list
      - name: SOLD
        link: se50oh
        scrape: true
        filter: false
        dealer: DEALER
        link_type: list
      - name: IN SALE
        link: se50j2
        scrape: true
        filter: true
        dealer: DEALER
        link_type: list
  - 
    dealear_type: PRIVATE
    file_name: resources/data/private_data.csv
    links:
      - name: ALL
        link: se5117
        scrape: false
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: SOLD
        link: se51bn
        scrape: true
        filter: false
        dealer: PRIVATE
        link_type: list
      - name: IN SALE
        link: se5165
        scrape: true
        filter: true
        dealer: PRIVATE
        link_type: list
  - 
    dealear_type: ALL
    file_name: resources/data/details.csv
    links:
      - name: ALL
        link: s9lr3v
        scrape: false
        filter: false
        dealer: None
        link_type: details
