equipment:
  9: "parktronic"
  10: "-"
  11: "tv_camera"
  12: "Застраховка"
  13: "heated_seats"
  14: "-"
  15: "-"
  16: "С регистрация"
  17: "_"
  18: "leather_seats"
  19: "panoramic_roof"
  20: "-"
  21: "Възможност за лизинг"
  22: "4x4 (4WD)"
  23: "-"
  24: "cruise_control"
  25: "abs"
  26: "esp"
  27: "aircondition(a_c)"
  28: "automatic_air_conditioning"
  29: "warranty"
  30: "gps"
  31: "tcs_asr"
  32: "keyless"
  33: "eco_start_stop"