equipment:
  9: "Парктроник"
  10: "-"
  11: "DVD/TV"
  12: "Застраховка"
  13: "Подгряване на седалки"
  14: "-"
  15: "-"
  16: "С регистрация"
  17: "Нов внос"
  18: "Кожен салон"
  19: "Панорамен покрив"
  20: "-"
  21: "Възможност за лизинг"
  22: "4x4"
  23: "-"
  24: "Автопилот"
  25: "ABC"
  26: "ESP"
  27: "Климатик"
  28: "Климатроник"
  29: "Гаранция"
  30: "Навигационна система"
  31: "ASR/Тракшън контрол"
  32: "Безключово палене"
  33: "Старт-Стоп система"