equipment:
  1: "Бензинов"
  2: "Дизелов"
  3: "Електрически"
  4: "Хибриден"
  5: "Plug-in хибрид"
  6: "Ръчна"
  7: "Автоматична"
  8: "Полуавтоматична"
  9: "Парктроник"
  10: "Система за контрол на дистанцията"
  11: "DVD, TV"
  12: "Каско"
  13: "Подгряване на седалките"
  14: "Адаптивно въздушно окачване"
  15: "Напълно обслужен"
  16: "С регистрация"
  17: "Нов внос"
  18: "Кожен салон"
  19: "Шибедах"
  20: "Метанова уредба"
  21: "Лизинг"
  22: "4x4"
  23: "Газова уредба"
  24: "Система за контрол на скоростта (автопилот)"
  