config:
  - 
    dealear_type: DEALER
    file_name: resources/data/dealers_data.csv
    links:
      - name: ALL
        link: s6xxgc
        scrape: false
        filter: false
      - name: SOLD
        link: s6xxbp
        scrape: true
        filter: false
      - name: IN SALE
        link: s6xv0s
        scrape: true
        filter: true
  - 
    dealear_type: PRIVATE
    file_name: resources/data/private_data.csv
    links:
      - name: ALL
        link: s6xxgc
        scrape: false
        filter: false
      - name: SOLD
        link: s6xxbp
        scrape: true
        filter: false
      - name: IN SALE
        link: s6xv0s
        scrape: true
        filter: true
