config:
  - 
    dealear_type: DEALER
    file_name: resources/data/dealers_data.csv
    links:
      - name: ALL
        link: s8s34t
        scrape: false
        filter: false
      - name: SOLD
        link: s8s3gb
        scrape: true
        filter: false
      - name: IN SALE
        link: s8s3nl
        scrape: true
        filter: true
  - 
    dealear_type: PRIVATE
    file_name: resources/data/private_data.csv
    links:
      - name: ALL
        link: s8s3to
        scrape: false
        filter: false
      - name: SOLD
        link: s8s40z
        scrape: true
        filter: false
      - name: IN SALE
        link: s8s45t
        scrape: true
        filter: true
  - 
    dealear_type: ALL
    file_name: resources/data/details.csv
    links:
      - name: ALL
        link: s9lr3v
        scrape: false
        filter: false
