// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseVehicleInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub make: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub title: ::prost::alloc::string::String,
    /// Assuming Currency is a defined enum or message
    #[prost(string, tag = "6")]
    pub currency: ::prost::alloc::string::String,
    /// Optional in Rust, so no 'optional' keyword needed in proto3
    #[prost(uint32, tag = "7")]
    pub price: u32,
    /// Optional in Rust, so no 'optional' keyword needed in proto3
    #[prost(uint32, tag = "8")]
    pub millage: u32,
    /// Optional in Rust, so no 'optional' keyword needed in proto3
    #[prost(uint32, tag = "9")]
    pub month: u32,
    #[prost(uint32, tag = "10")]
    pub year: u32,
    /// Assuming Engine is a defined message
    #[prost(string, tag = "11")]
    pub engine: ::prost::alloc::string::String,
    /// Assuming Gearbox is a defined message
    #[prost(string, tag = "12")]
    pub gearbox: ::prost::alloc::string::String,
    #[prost(uint32, tag = "13")]
    pub cc: u32,
    #[prost(uint32, tag = "14")]
    pub power_ps: u32,
    #[prost(uint32, tag = "15")]
    pub power_kw: u32,
    #[prost(string, tag = "16")]
    pub search_id: ::prost::alloc::string::String,
    #[prost(string, tag = "17")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetailedVehicleInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub location: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub equipment: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub seller_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub seller_url: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub range: u32,
    #[prost(float, tag = "8")]
    pub consumption_fuel: f32,
    #[prost(float, tag = "9")]
    pub consumption_kw: f32,
    #[prost(uint32, tag = "10")]
    pub co2: u32,
    #[prost(uint32, tag = "11")]
    pub days_in_sale: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Price {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    /// Optional in Rust, so no 'optional' keyword needed in proto3
    #[prost(uint32, tag = "3")]
    pub estimated_price: u32,
    #[prost(uint32, tag = "4")]
    pub price: u32,
    /// Assuming Currency is defined in enums.proto
    #[prost(string, tag = "5")]
    pub currency: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub save_difference: u32,
    #[prost(uint32, tag = "7")]
    pub overpriced_difference: u32,
    /// Optional in Rust, so no 'optional' keyword needed in proto3
    #[prost(string, tag = "8")]
    pub ranges: ::prost::alloc::string::String,
    /// Optional in Rust, so no 'optional' keyword needed in proto3
    #[prost(string, tag = "9")]
    pub rating: ::prost::alloc::string::String,
    /// For 'thresholds', protobuf doesn't support Vec directly. You might consider using repeated field.
    #[prost(uint32, repeated, tag = "10")]
    pub thresholds: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Id {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadStatus {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub listed: u32,
    #[prost(uint32, tag = "5")]
    pub actual: u32,
    #[prost(string, tag = "6")]
    pub hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EurExchangeRate {
    #[prost(string, tag = "1")]
    pub currency: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub eur_exchange_rate: f32,
    #[prost(string, tag = "3")]
    pub created_on: ::prost::alloc::string::String,
}
